# Generated by Django 4.0.6 on 2022-07-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_receipt_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('d', 'debit'), ('c', 'credit')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Master', 'Mstercard'), ('Visa', 'Visacard')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_picture/'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdrawal'), ('depo', 'deposit')], max_length=10, null=True),
        ),
    ]
